### ISSUE TITLE
.save segfaults on v2021.10-104-g5f8441024

### ISSUE THREAD

**Issue by jonathanstowe** [jnthn/spreadsheet-xlsx#14]
This is more of a headsup to https://github.com/libxml-raku/LibXML-raku/issues/65 but it's causing `.save` to segfault on

```
Welcome to Rakudo™ v2021.10-104-g5f8441024.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2021.10-69-g592cc8548.
```

**Comment by jnthn** [comment]
I came across this yesterday, actually when looking into if spreadsheet generation leaks memory. I think this may be a MoarVM issue, since it goes away with `MVM_SPESH_DISABLE=1`. I see this:

```
Thread 1 "rakudo-m" received signal SIGSEGV, Segmentation fault.
0x00007ffff798156d in MVM_disp_program_run (tc=tc@entry=0x55555555a120, 
    dp=dp@entry=0x5555599337c0, record=0x7ffff6f2d050, spesh_cid=spesh_cid@entry=0, 
    bytecode_offset=bytecode_offset@entry=174, dp_index=dp_index@entry=0)
    at src/disp/program.c:3333
3333	                if (STABLE(val.o)->hll_owner != dp->constants[op.arg_guard.checkee].hll)
(gdb) where
#0  0x00007ffff798156d in MVM_disp_program_run (tc=tc@entry=0x55555555a120, 
    dp=dp@entry=0x5555599337c0, record=0x7ffff6f2d050, spesh_cid=spesh_cid@entry=0, 
    bytecode_offset=bytecode_offset@entry=174, dp_index=dp_index@entry=0)
    at src/disp/program.c:3333
#1  0x00007ffff7977881 in dispatch_monomorphic (tc=0x55555555a120, entry_ptr=0x55555b105ab8, 
    seen=0x55555b143af0, id=<optimized out>, callsite=<optimized out>, 
    arg_indices=0x7fffeb35a120, source=0x7ffff6f2ce90, sf=<optimized out>, bytecode_offset=174)
    at src/disp/inline_cache.c:107
#2  0x00007ffff78ea13e in MVM_interp_run (tc=0x7ffff6f2d088, initial_invoke=0x5555599337c0, 
    invoke_data=0x5555599337c0, outer_runloop=0x7ffff7e2fce0 <LABELS.25770>)
    at src/core/interp.c:5345
#3  0x00005555555558e9 in main ()
(gdb) p MVM_dump_backtrace(tc)
   at site#sources/729BC332BDE261CD3113447E766A4D3DC2A66D81 (LibXML::Node):160  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/72/729BC332BDE261CD3113447E766A4D3DC2A66D81:box)
 from site#sources/B3FD61BB992B38720A29D15291A08301C5B2AD68 (LibXML::Document):564  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/B3/B3FD61BB992B38720A29D15291A08301C5B2AD68:createElementNS)
 from site#sources/76F75F9A22D1864EEA46984ABF358978110E71F6 (Spreadsheet::XLSX::Worksheet):375  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/76/76F75F9A22D1864EEA46984ABF358978110E71F6:)
 from site#sources/76F75F9A22D1864EEA46984ABF358978110E71F6 (Spreadsheet::XLSX::Worksheet):372  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/76/76F75F9A22D1864EEA46984ABF358978110E71F6:to-xml)
 from site#sources/76F75F9A22D1864EEA46984ABF358978110E71F6 (Spreadsheet::XLSX::Worksheet):365  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/76/76F75F9A22D1864EEA46984ABF358978110E71F6:sync-to-archive)
 from site#sources/5B4B48019FAFDDDACE519E763FAA24271A393597 (Spreadsheet::XLSX::Workbook):152  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/5B/5B4B48019FAFDDDACE519E763FAA24271A393597:)
 from site#sources/5B4B48019FAFDDDACE519E763FAA24271A393597 (Spreadsheet::XLSX::Workbook):151  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/5B/5B4B48019FAFDDDACE519E763FAA24271A393597:sync-to-archive)
 from site#sources/6B95368FA292C8C986B317BAD740379DEB60E17C (Spreadsheet::XLSX):178  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/6B/6B95368FA292C8C986B317BAD740379DEB60E17C:sync-to-archive)
 from site#sources/6B95368FA292C8C986B317BAD740379DEB60E17C (Spreadsheet::XLSX):150  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/6B/6B95368FA292C8C986B317BAD740379DEB60E17C:to-blob)
 from site#sources/6B95368FA292C8C986B317BAD740379DEB60E17C (Spreadsheet::XLSX):170  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/6B/6B95368FA292C8C986B317BAD740379DEB60E17C:save)
 from site#sources/6B95368FA292C8C986B317BAD740379DEB60E17C (Spreadsheet::XLSX):165  (/home/jnthn/.raku/precomp/06A1012BDB921BAF9F34DDB2A83C288984BA63F2/6B/6B95368FA292C8C986B317BAD740379DEB60E17C:save)
 from leak.raku:26  (<ephemeral file>:<unit>)
 from leak.raku:1  (<ephemeral file>:<unit-outer>)
 from gen/moar/stage2/NQPHLL.nqp:1949  (/home/jnthn/dev/MoarVM/install/share/nqp/lib/NQPHLL.moarvm:eval)
 from gen/moar/stage2/NQPHLL.nqp:2154  (/home/jnthn/dev/MoarVM/install/share/nqp/lib/NQPHLL.moarvm:evalfiles)
 from gen/moar/stage2/NQPHLL.nqp:2084  (/home/jnthn/dev/MoarVM/install/share/nqp/lib/NQPHLL.moarvm:command_eval)
 from gen/moar/Compiler.nqp:111  (/home/jnthn/dev/MoarVM/install/share/perl6/lib/Perl6/Compiler.moarvm:command_eval)
 from gen/moar/stage2/NQPHLL.nqp:2039  (/home/jnthn/dev/MoarVM/install/share/nqp/lib/NQPHLL.moarvm:command_line)
 from gen/moar/rakudo.nqp:127  (/home/jnthn/dev/MoarVM/install/share/perl6/runtime/perl6.moarvm:MAIN)
 from gen/moar/rakudo.nqp:1  (/home/jnthn/dev/MoarVM/install/share/perl6/runtime/perl6.moarvm:<mainline>)
 from <unknown>:1  (/home/jnthn/dev/MoarVM/install/share/perl6/runtime/perl6.moarvm:<main>)
 from <unknown>:1  (/home/jnthn/dev/MoarVM/install/share/perl6/runtime/perl6.moarvm:<entry>)
$2 = void
```

Which suggest `val.o` is either a real `NULL` (should not happen) or otherwise a bogus `MVMObject` pointer (also bad).

**Comment by jonathanstowe** [comment]
This has definitely gone away now.
